### ISSUE TITLE
Folder ownership problem

### ISSUE THREAD

**Issue by snielson** [chadlyalan/SR-Directory-Sync#3]
Folders created in open/closed do not have the correct ownership for my folder structure.

Default from script:
root:root

Expected ownership:
gwsupport:users

Since this may vary from user to user, I may suggest a config file to get the correct owner

**Comment by chadlyalan** [comment]
I created a fixit script that is now up if you've used the srsync script to create directories in the past, as they do in fact create the directories with the wrong ownerships.
